apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 2
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: hzhyvinskyi/iam-solutions-user-service:1.0.0
          env:
            - name: SERVICE_NAME
              value: "User Service"
            - name: SERVICE_HOSTNAME
              value: "user-service"
            - name: SERVICE_PORT
              value: "8088"
